### ISSUE TITLE
[BUG]  TKOSubsScan Error providers-data.csv missing

### ISSUE THREAD

**Issue by Bad3r** [epi052/recon-pipeline#68]
**Describe the bug**
The `TKOSubsScan` scan fails due to the file  `providers-data.csv` being missing
```
INFO: [pid 114307] Worker Worker(salt=334832822, workers=1, host=GLaD0S, username=root, pid=114307, sudo_user=bad3r) running   TKOSubsScan(target_file=/tmp/tmpj58rd_um, db_location=/root/.local/recon-pipeline/databases/testing, results_dir=/home/bad3r/tmp/scan-results, exempt_list=, rate=500, interface=enp0s31f6, top_ports=100, ports=)
Error: open None/providers-data.csv: no such file or directory
Usage of /root/.local/recon-pipeline/tools/pipeline-go-workspace/bin/tko-subs:
  -data string
    	CSV file containing CMS providers' string for identification (default "providers-data.csv")
  -domain string
    	Domains separated by ,
  -domains string
    	List of domains to check (default "domains.txt")
  -githubtoken string
    	Github personal access token
  -herokuapikey string
    	Heroku API key
  -herokuappname string
    	Heroku app name
  -herokuusername string
    	Heroku username
  -output string
    	Output file to save the results (default "output.csv")
  -takeover
    	Flag to denote if a vulnerable domain needs to be taken over or not
  -threads int
    	Number of threads to run parallel (default 5)
ERROR: [pid 114307] Worker Worker(salt=334832822, workers=1, host=GLaD0S, username=root, pid=114307, sudo_user=bad3r) failed    TKOSubsScan(target_file=/tmp/tmpj58rd_um, db_location=/root/.local/recon-pipeline/databases/testing, results_dir=/home/bad3r/tmp/scan-results, exempt_list=, rate=500, interface=enp0s31f6, top_ports=100, ports=)
Traceback (most recent call last):
  File "/home/bad3r/.local/share/virtualenvs/recon-pipeline-B_t2qNnz/lib/python3.8/site-packages/luigi/worker.py", line 199, in run
    new_deps = self._run_get_new_deps()
  File "/home/bad3r/.local/share/virtualenvs/recon-pipeline-B_t2qNnz/lib/python3.8/site-packages/luigi/worker.py", line 141, in _run_get_new_deps
    task_gen = self.task.run()
  File "/home/bad3r/git/recon-pipeline/pipeline/recon/web/subdomain_takeover.py", line 132, in run
    self.parse_results()
  File "/home/bad3r/git/recon-pipeline/pipeline/recon/web/subdomain_takeover.py", line 88, in parse_results
    with open(self.output_file, newline="") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/bad3r/tmp/scan-results/tkosubs-results/tkosubs.csv'
```

**To Reproduce**
1. follow installation instructions
2. create a database and attach it
3. run a `TKOSubsScan`
```
scan TKOSubsScan --results-dir /home/bad3r/tmp/scan-results --target secbytes.net --top-ports 100 --rate 500 --interface enp0s31f6 --verbose
```

**Expected behavior**
the file `providers-data.csv` should exist before the `TKOSubsScan` starts

**Environment (please complete the following information):**
- recon-pipeline version: 0.10.3
- python version: 3.8.3
- OS: Arch Linux

**Additional context**
I am not sure why the parent directory shows as `None`
```
open None/providers-data.csv: no such file or directory
```
initially i noticed the error while running a `FullScan`

**Comment by Bad3r** [comment]
that fixed it thanks!

**Comment by epi052** [comment]
Thanks for checking the fix!  I'm going to reopen this in order to track the problem until i get a PR in to fix it.
