### ISSUE TITLE
Issue after upgrading to Big Sur

### ISSUE THREAD

**Issue by ghost** [epi052/recon-pipeline#95]
**Describe the bug**

Can't install tools, only go was able to be installed with an error. 
Using "tools install all" or installing tools one by one, would also issue an error.

**To Reproduce**
1. tools list
2. tools install all

**Expected behavior**
To install all tools. Using the command "tools install all".

**Traceback / Error Output**

[!] bash: line 0: [: PATH=/Users/mk/.local/share/virtualenvs/recon-pipeline-O1OVDp4l/bin:/usr/local/Cellar/pipenv/2020.11.15/libexec/tools:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/VMware: unary operator expected
[+] go installed!

If I tried to install the tools manually one by one it would also issues an error. For example installing amass:

[*] Installing amass...
[=] /Users/mk/.local/recon-pipeline/tools/pipeline-go/go/bin/go get github.com/OWASP/Amass/v3/...
EXCEPTION of type 'OSError' occurred with message: '[Errno 8] Exec format error: '/Users/mk/.local/recon-pipeline/tools/pipeline-go/go/bin/go''
To enable full traceback, run the following command: 'set debug true'

If I set debug true. It would display this:

[*] Installing amass...
[=] /Users/mk/.local/recon-pipeline/tools/pipeline-go/go/bin/go get github.com/OWASP/Amass/v3/...
Traceback (most recent call last):
  File "/Users/mk/.local/share/virtualenvs/recon-pipeline-O1OVDp4l/lib/python3.9/site-packages/cmd2/cmd2.py", line 1657, in onecmd_plus_hooks
    stop = self.onecmd(statement, add_to_history=add_to_history)
  File "/Users/mk/.local/share/virtualenvs/recon-pipeline-O1OVDp4l/lib/python3.9/site-packages/cmd2/cmd2.py", line 2064, in onecmd
    stop = func(statement)
  File "/Users/mk/.local/share/virtualenvs/recon-pipeline-O1OVDp4l/lib/python3.9/site-packages/cmd2/decorators.py", line 223, in cmd_wrapper
    return func(cmd2_app, args)
  File "/Users/mk/Tools/recon-pipeline/./pipeline/recon-pipeline.py", line 510, in do_tools
    func(args)
  File "/Users/mk/Tools/recon-pipeline/./pipeline/recon-pipeline.py", line 439, in tools_install
    proc = subprocess.Popen(
  File "/usr/local/Cellar/python@3.9/3.9.0_2/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 947, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/Cellar/python@3.9/3.9.0_2/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 1819, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: '/Users/mk/.local/recon-pipeline/tools/pipeline-go/go/bin/go'
EXCEPTION of type 'OSError' occurred with message: '[Errno 8] Exec format error: '/Users/mk/.local/recon-pipeline/tools/pipeline-go/go/bin/go''

**Environment (please complete the following information):**
 - recon-pipeline version: [ v1.0.1 ]
 - python version [Python 3.9.0]
 - OS [MacOS Big Sur 11.0.1]

**Additional context*

**Comment by epi052** [comment]
Howdy! OSX isn't a supported operating system. However, after a cursory search, I came across this https://stackoverflow.com/questions/27606653/oserror-errno-8-exec-format-error.  Since it's an amass install, you could try using the pipeline's version of go (`/Users/mk/.local/recon-pipeline/tools/pipeline-go/go`) to manually install amass
